[package]
edition = "2021"
name = "sublist"
version = "0.0.0"

[dev-dependencies]
criterion = "0.5"

# name below should be the name of a source under ./benches
[[bench]]
name = "sublist_benchmark"
harness = false